

%% Please use double quotation marks for large text, otherwise characters such as Chinese punctuation cannot be used
%% HTML syntax is supported within the text, such as line breaks, please use

%% support for Font Awesome icons
%% For more syntax, see [Mermaid flowchart syntax](https://mermaidjs.github.io/flowchart.html)

graph TB

tag(fa:fa-tag ver. 1.1)
style tag fill: #0000000a, stroke: #bfbfbf

start["How to choose V2Ray scheme fa:fa-rocket"] -->
  simple-way?(-"Mengxin? Too lazy to toss? In a hurry?"-)

simple-way? -->
  |No| speed?(-"Do you want speed? Or stability?"-)
simple-way? -->
  |Yes| buy["Buy, buy, buy! Please search for <br> paid VPN SS V2Ray by yourself 
, <br> which is convenient, fast, <br> time-saving and labor-saving!"]

speed? --> |stable| worry-sniff?(-"Mind if you might be detected using V2Ray?"-)
speed? --> |speed| kcp["fa:fa-star KCP"]

%% speed branch

kcp --> more-speed?(-"Simple KCP speed is not ideal? <br> Want to try a more complex configuration?"-)
more-speed? -->
  |Yes| kcp-udp2raw["fa:fa-star fa:fa-star fa:fa-star try KCP + udp2raw 
*note that udp2raw is difficult to use on mobile clients "]

kcp-udp2raw --> more-more-speed?(-"Still not powerful?"-)
more-more-speed? -->
  |"Yeah! I feel cheated!"| tcp-bbr["
    fa:fa-star fa:fa-star fa:fa-star Adjust KCP parameters or try TCP + BBR <br>

    *Note that BBR requires specific system support, <br> please refer to related tutorials. <br>

    Since it is a low-level unilateral algorithm,<br> it can be used in combination with other options
  "]

%% stable branch

worry-sniff? -->
  |Don't worry about it | tcp-vmess["fa:fa-star TCP + Vmess"]
worry-sniff? -->
  |Working secretly| have-website?(-"Do you know how to build a website? <br> Is 
a website already running on the server?"-)

have-website? -->
  |"No, don't know and don't want to know"| ws-or-obfu["fa:fa-star WebSocket, HTTP/2 or Vmess + masquerading"]
have-website? -->
  |"Yes! Coach! I want to learn this!"| https?(-"Want to hide V2Ray further? Does 
the site support HTTPS?"-)

https? -->
  |It's always better to be safe | https-website["
    fa:fa-star fa:fa-star Caddy + TLS + WebSocket, HTTP/2

    fa:fa-star fa:fa-star fa:fa-star Nginx/Apache/Other + TLS + WebSocket, HTTP/2
  "]
https? -->
  |"Forget it, it's too much trouble"| website["fa:fa-star fa:fa-star Caddy/Nginx/Apache/Other + WebSocket"]

website --> cdn?
https-website --> cdn?
cdn?(-"Want to protect the host IP from being killed? <br>
Even if the speed may be affected indefinitely?"-) -->
  |"Yes, it's a little bit more stable"| cdn["fa:fa-star fa:fa-star Cloudflare and other CDNs 
*Note that this difficulty level is unique to CDNs "]


note(" 
fa:fa-star indicates the complexity level, the more fa:fa-star, <br> the more complex and difficult it is 

.Some options  <br> in the speed classification and stability classification <br> can be used in combination

To participate in <br> modifying this picture, please go to github.com/v2fly/vTemplate
")

style note stroke-width: 2px, stroke-dasharray: 5.5

